menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/tomohung
    Rss: /atom.xml

favicon: /photo.jpg
logo: /photo.jpg

# Comment
# e.g disqus: seansun
disqus: tomohung
duoshuo:

# Analytics
# google-analytics:
ga: UA-12830335-2

# Copyright Infomation
startyear: 2015
